import {
	GetServerSideProps,
	InferGetServerSidePropsType,
	type NextPage
} from 'next'
import Head from 'next/head'
import { Header } from 'components/layout/header/header'
import { api } from '~/utils/api'
import { Loader } from '@mantine/core'
import { Item } from 'components/pages/item/item'

const ItemPage: NextPage = ({
	query
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	const { data, isLoading } = api.product.getProductById.useQuery({
		id: query.id
	})
	if (isLoading) {
		return (
			<div className='basis-3/4'>
				<Loader className='mx-auto' />
			</div>
		)
	}
	if (!isLoading && !data) {
		return <>{'No Data'}</>
	}
	return (
		<>
			<Head>
				<title>Item Name </title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='font-body'>
				<Header />
				<div className='cont flex pt-4 gap-12'>
					<Item
						data={{
							id: data!.id,
							title: data!.title,
							description: data!.description,
							brand: data!.brand,
							price: data!.price,
							rating: data!.rating,
							images: data!.images
						}}
					/>
				</div>
			</main>
		</>
	)
}

export const getServerSideProps: GetServerSideProps = async ctx => {
	const query = ctx.params
	return { props: { query } }
}

export default ItemPage
