import { type NextPage } from 'next'
import Head from 'next/head'
import { Header } from 'components/layout/header/header'
import { CategoryBar } from 'components/layout/category-bar/category-bar'
import { ItemGrid } from 'components/layout/item-grid/item-grid'

const CategoryPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Category Name </title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='font-body'>
				<Header />
				<div className='cont flex pt-4 gap-12'>
					<div className='basis-1/4 filter-bar-cont md:block hidden'>
						<CategoryBar />
					</div>
					<ItemGrid />
				</div>
			</main>
		</>
	)
}

export default CategoryPage
