import { type NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Header } from '../../components/layout/header/header'
import { CategoryBar } from 'components/layout/category-bar/category-bar'
import { api } from '~/utils/api'
import { ItemGrid } from '../../components/layout/item-grid/item-grid'
import { Loader } from '@mantine/core'

const Home: NextPage = () => {
	const { data, isLoading } = api.product.getAllProducts.useQuery()
	return (
		<>
			<Head>
				<title>t3-store </title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className='font-body cont-t'>
				<div className='flex pt-4 gap-12'>
					<div className='basis-1/4 filter-bar-cont md:block hidden'>
						<CategoryBar />
					</div>
					{isLoading ? (
						<div className='basis-3/4'>
							<Loader className='mx-auto' />
						</div>
					) : (// @ts-ignore comment 
						<ItemGrid data={data} />
					)}
				</div>
			</main>
		</>
	)
}

export default Home
