import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '~/utils/api'
import React from 'react'
import { Header } from '../../components/layout/header/header'
import { FilterBar } from 'components/layout/filter-bar/filter-bar'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>t3-store </title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className=''>
				<Header />
				<div className='cont flex h-screen pt-4 gap-4	'>
					<div className='filter-bar-cont'> 
						<FilterBar />
					</div>
					<div className='main-cont h-screen bg-green-300'>
						
					</div>
				</div>
			</main>
		</>
	)
}

export default Home
