import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '~/utils/api'
import React from 'react'
import { Header } from '../../components/layout/header'

const Home: NextPage = () => {
	const user = api.user.me.useQuery()

	console.log(user.data)

	return (
		<>
			<Head>
				<title>t3-store </title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className=''>
				<Header />
				<div className='cont'></div>
			</main>
		</>
	)
}

export default Home
